"""Telemetry field contracts, independent of Arrow and filesystem adapters."""
from __future__ import annotations

TELEMETRY_SCHEMA = "qcl-negf.performance.v2"
# Types map to Arrow types at the adapter boundary; units remain explicit in names.
COMMON_FIELDS = (("session_id", "string"), ("worker_id", "string"),
                 ("execution_id", "string"), ("point_id", "string"),
                 ("allocation_id", "string"), ("monotonic_ns", "int64"),
                 ("sample_sequence", "int64"), ("clock_domain_id", "string"),
                 ("utc_anchor_ns", "int64"), ("monotonic_anchor_ns", "int64"))
SPAN_FIELDS = COMMON_FIELDS + (("span_id", "string"), ("parent_span_id", "string"),
    ("phase", "string"), ("duration_seconds", "float64"), ("call_count", "int64"),
    ("iteration", "int64"), ("timing_kind", "string"), ("warmup", "bool"),
    ("measurement_kind", "string"), ("timestamp_kind", "string"),
    ("source_session_id", "string"), ("source_sequence", "int64"),
    ("source_path", "string"), ("source_offset", "int64"),
    ("stage_path", "string"), ("attempt", "int64"),
    ("may_include_compilation", "bool"), ("payload_bytes", "int64"),
    ("event_kind", "string"), ("begin_monotonic_ns", "int64"),
    ("end_monotonic_ns", "int64"), ("process_cpu_seconds", "float64"),
    ("allocated_bytes", "int64"), ("gc_seconds", "float64"), ("gc_count", "int64"),
    ("counter_scope", "string"), ("process_cpu_total_seconds", "float64"),
    ("allocated_total_bytes", "int64"), ("gc_total_seconds", "float64"),
    ("gc_total_count", "int64"), ("task_width", "int64"),
    ("work_units", "int64"), ("workspace_bytes", "int64"),
    ("memory_burst_bytes", "int64"), ("parallel_kind", "string"),
    ("phase_wait_reason", "string"), ("capability_reasons", "string"),
    ("memory_admission_mode", "string"), ("memory_current_before_bytes", "int64"),
    ("memory_limit_bytes", "int64"), ("memory_granted_additional_bytes", "int64"),
    ("memory_current_after_gc_bytes", "int64"), ("memory_effective_current_bytes", "int64"),
    ("memory_clean_cache_credit_bytes", "int64"), ("memory_full_gc_seconds", "float64"),
    ("memory_stat_before", "string"), ("memory_stat_after_gc", "string"))
RESOURCE_FIELDS = COMMON_FIELDS + (("cpu_time_seconds", "float64"),
    ("wall_seconds", "float64"), ("rss_bytes", "int64"), ("peak_rss_bytes", "int64"),
    ("cpu_count", "int64"), ("read_bytes", "int64"), ("write_bytes", "int64"),
    ("gc_seconds", "float64"), ("throttled_seconds", "float64"),
    ("cpu_pressure_seconds", "float64"), ("sample_interval_seconds", "float64"),
    ("missing_reason", "string"), ("capability_reasons", "string"),
    ("pid", "int64"), ("process_start_ticks", "int64"),
    ("cgroup_path", "string"), ("cgroup_scope", "string"),
    ("cgroup_cpu_seconds", "float64"), ("cpu_quota_cores", "float64"),
    ("cpu_period_seconds", "float64"), ("throttled_periods", "int64"),
    ("memory_current_bytes", "int64"), ("memory_peak_bytes", "int64"),
    ("memory_high_bytes", "int64"), ("memory_max_bytes", "int64"),
    ("memory_anon_bytes", "int64"), ("memory_file_bytes", "int64"),
    ("memory_kernel_bytes", "int64"), ("memory_swap_bytes", "int64"),
    ("memory_inactive_file_bytes", "int64"), ("memory_file_dirty_bytes", "int64"),
    ("memory_file_writeback_bytes", "int64"), ("memory_shmem_bytes", "int64"),
    ("memory_file_mapped_bytes", "int64"),
    ("memory_event_high", "int64"), ("memory_event_max", "int64"),
    ("memory_event_oom", "int64"), ("memory_event_oom_kill", "int64"),
    ("memory_event_oom_group_kill", "int64"),
    ("memory_pressure_seconds", "float64"), ("io_pressure_seconds", "float64"),
    ("cpu_full_pressure_seconds", "float64"),
    ("memory_full_pressure_seconds", "float64"), ("io_full_pressure_seconds", "float64"),
    ("minor_faults", "int64"), ("major_faults", "int64"),
    ("voluntary_context_switches", "int64"), ("involuntary_context_switches", "int64"),
    ("thread_count", "int64"), ("thread_cpu_seconds", "string"),
    ("thread_counter_scope", "string"), ("thread_counter_details", "string"),
    ("thread_listed_count", "int64"), ("thread_sample_count", "int64"),
    ("thread_sampling_complete", "bool"), ("thread_delta_complete", "bool"),
    ("matched_thread_count", "int64"), ("new_thread_count", "int64"),
    ("vanished_thread_count", "int64"), ("thread_counter_interval_seconds", "float64"),
    ("voluntary_context_switches_delta", "int64"), ("involuntary_context_switches_delta", "int64"),
    ("thread_runtime_seconds", "float64"), ("thread_runtime_delta_seconds", "float64"),
    ("thread_runqueue_wait_seconds", "float64"), ("thread_runqueue_wait_delta_seconds", "float64"),
    ("thread_schedstat_enabled", "bool"),
    ("profile_window_id", "string"), ("sampling_mode", "string"),
    ("active_task_width", "int64"), ("phase", "string"))
CONTROL_FIELDS = COMMON_FIELDS + (("event", "string"), ("reason", "string"),
    ("attempt", "int64"), ("reference", "string"), ("samples_dropped", "int64"))
TABLE_FIELDS = {"spans": SPAN_FIELDS, "resources": RESOURCE_FIELDS, "control_events": CONTROL_FIELDS}
